version: '3.1'

services:

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: DuyBua
      POSTGRES_PASSWORD: testpassword
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: